apiVersion: v1
kind: Service
metadata:
  name: colorsplash
  labels:
    app: colorsplash
spec:
  type: LoadBalancer
  selector:
    app: colorsplash
  ports:
    - name: http
      port: 80
      targetPort: 5000
